# Generated by Django 3.0.5 on 2021-06-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='is_deployed',
            field=models.BooleanField(default=False),
        ),
    ]
