# Generated by Django 3.0.5 on 2021-05-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='is_deployed',
            field=models.BooleanField(default=False),
        ),
    ]
