# Generated by Django 3.0.5 on 2021-06-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_remove_formentry_is_deployed'),
    ]

    operations = [
        migrations.AddField(
            model_name='formentry',
            name='is_deployed',
            field=models.BooleanField(default=False),
        ),
    ]
